version: '3'

services:
  justsaledb:
      container_name: justsaledb
      image: postgres:13.0
      environment:
        - POSTGRES_USER=justsale
        - POSTGRES_PASSWORD=justsalepass
        - POSTGRES_DB=justsaledb
      expose: 
        - 5432
      ports:
        - 5432:5432
  justsaleweb:
      container_name: justsaleweb
      build: .
      command: 'python3 manage.py runserver 0.0.0.0:8000'
      volumes:
        - .:/app
      ports:
        - '8000:8000'
      env_file:
        - '.env'
      depends_on:
        - justsaledb
